CREATE TABLE GAT_PLAN(
    GAT_PLAN_DATE varchar2(50),
    GAT_PLAN_ADDR VARCHAR2(50),
    GAT_PLAN_ADDR2 VARCHAR2(50),
    GAT_PLAN_TITLE VARCHAR2(50),
    GAT_PLAN_DESC VARCHAR2(50)
);


SELECT * from GAT_PLAN;
 DELETE GAT_PLAN;
 commit;

drop table GAT_PLAN;
INSERT INTO GAT_PLAN(GAT_PLAN_DATE, GAT_PLAN_ADDR, GAT_PLAN_ADDR2, 
GAT_PLAN_TITLE, GAT_PLAN_DESC)
        VALUES ('a','b','c','d','e');
        
       